	document.write('<div id="leftWingBn">');
	document.write('<dl>');
	document.write('<dt><img src="http://img.danawa.com/new/GNB/img/hotCate_tit.gif" /></dt>');
	document.write('<dd><a href="http://www.danawa.com/product/list.html?defSite=ELEC&cate_c1=197&cate_c2=532&cate_c3=0&cate_c4=0" title="MP3" onMouseDown="_trkEventLog(\'집중카테고리_MP3\')">MP3</a></dd>');
	document.write('<dd><a href="http://www.danawa.com/product/list.html?defSite=ELEC&cate_c1=149&cate_c2=1360&cate_c3=0&cate_c4=0" title="PMP" onMouseDown="_trkEventLog(\'집중카테고리_PMP\')">PMP</a></dd>');
	document.write('<dd><a href="http://www.danawa.com/product/list.html?defSite=ELEC&cate_c1=118&cate_c2=119&cate_c3=0&cate_c4=0" title="에어컨" onMouseDown="_trkEventLog(\'집중카테고리_에어컨\')">에어컨</a></dd>');
	document.write('<dd><a href="http://www.danawa.com/product/list.html?defSite=SPORTS&cate_c1=1825&cate_c2=9497" title="골프" onMouseDown="_trkEventLog(\'집중카테고리_골프\')">골프</a></dd>');
	document.write('<dd><a href="http://pc.danawa.com/price.html?defSite=PC&cate1=860&cate2=865" title="표준PC" onMouseDown="_trkEventLog(\'집중카테고리_표준PC\')">표준PC</a></dd>');
	document.write('<dd class="combot"></dd>');
	document.write('</dl>');
	document.write('</div>');
